class Pokemon < ActiveHash::Base
  self.data = [
    { id: 1, name: 'フシギダネ', category: 'たね', type: '草',characteristic: 'しんりょく', explain: "生まれた時から背中に植物のたねがあって少しずつ大きく育つ。"},
    { id: 2, name: 'フシギソウ', category: 'たね', type: '草',characteristic: 'しんりょく', explain: '太陽の光を浴びるほど、体に力が湧いて背中のつぼみが育っていく。'},
    { id: 3, name: 'フシギバナ', category: 'たね', type: '草',characteristic: 'しんりょく', explain: '太陽エネルギーを栄養にして、大きな花が開く。日向に引き寄せられるように移動する。'},
    { id: 4, name: 'ヒトカゲ', category: 'トカゲ', type: '炎', characteristic: 'もうか', explain: '生まれた時から、尻尾に炎が灯っている。炎が消えた時、その命は終わってしまう。' },
    { id: 5, name: 'リザードン', category: '火炎', type: '炎、飛行', characteristic: 'もうか', explain: '地上1400メートルまで、翼を使って飛ぶことができる。高熱の炎を吐く。' },
    { id: 6, name: 'リザード', category: '火炎', type: '炎、', characteristic: 'もうか', explain: '燃える尻尾を振りまわし、鋭い爪で相手を切り裂く、荒々しい性格。' },
    { id: 7, name: 'ゼニガメ', category: 'かめのこ', type: '水', characteristic: 'げきりゅう', explain: '危なくなると、甲羅に手足を引っ込めて身を守りながら、口から水を噴き出してくる。' },
    { id: 8, name: 'カメール', category: 'かめ', type: '水', characteristic: 'げきりゅう', explain: '長生きのシンボルとされている。甲羅に苔が生えているのは、特に長生きのカメールだ。' },
    { id: 9, name: 'カメックス', category: '甲羅', type: '水', characteristic: 'げきりゅう', explain: '甲羅のロケット砲から噴き出したジェット水流は、分厚い鉄板も貫く。' },
    { id: 10, name: 'キャタピー', category: 'いもむし', type: '虫', characteristic: 'りんぷん', explain: '頭の触覚から強烈な匂いを出して、敵をおいはらい身を守る。' },
    { id: 11, name: 'トランセル', category: 'さなぎ', type: '虫', characteristic: 'だっぴ', explain: '進化を待っている状態。硬くなることしかできないので、襲われないようにじっとしている。' },
    { id: 12, name: 'バタフリー', category: 'ちょうちょ', type: '虫、飛行', characteristic: 'ふくがん', explain: '毎日蜜を集め回る。足のうぶげに蜜を塗り込んで巣に持ち帰る習性を持つ。' },
    { id: 13, name: 'ビードル', category: 'けむし', type: '虫、毒', characteristic: 'りんぷん', explain: '森や草地に多く生息している。頭の先に5センチくらいの鋭いどくばりを持つ。' },
    { id: 14, name: 'コクーン', category: 'さなぎ', type: '虫、毒', characteristic: 'だっぴ', explain: '自分ではほとんど動けないが、危ない時は硬くなって身を守っているようだ。' },
    { id: 15, name: 'スピアー', category: 'どくばち', type: '虫、毒', characteristic: 'むしのしらせ', explain: '両手とお尻にあるどくばりで、相手を刺して刺して刺しまくって攻撃する。' },
    { id: 16, name: 'ポッポ', category: 'ことり', type: 'ノーマル、飛行', characteristic: 'するどいめ、ちどりあし', explain: '森や林に多く分布している。地上でも激しくはばたいて、砂をかけたりする。' },
    { id: 17, name: 'ピジョン', category: 'とり', type: 'ノーマル、飛行', characteristic: 'するどいめ、ちどりあし', explain: '足の爪が発達している。餌のタマタマを掴んで、100キロ先の巣まで運ぶ。' },
    { id: 18, name: 'ピジョット', category: 'とり', type: 'ノーマル、飛行', characteristic: 'するどいめ、ちどりあし', explain: '美しい羽を広げて相手を威嚇する。マッハ2で空を飛び回る。' },
    { id: 19, name: 'コラッタ', category: 'ねずみ', type: 'ノーマル', characteristic: 'にげあし、こんじょう', explain: '前歯は死ぬまで伸び続けるので、メンテナンスが必要。ヤスリを用意しないと、柱をかじられる。' },
    { id: 20, name: 'ラッタ', category: 'ねずみ', type: 'ノーマル', characteristic: 'にげあし、こんじょう', explain: '見た目よりもずっと凶暴な性質。顔の前に手を伸ばすと噛みちぎられるかも。' },
    { id: 21, name: 'オニスズメ', category: 'ことり', type: 'ノーマル、飛行', characteristic: 'するどいめ', explain: '羽が短く、飛ぶのは苦手。せわしなく動き回り、草むらの虫ポケモンをついばんでいる。' },
    { id: 22, name: 'オニドリル', category: 'くちばし', type: 'ノーマル、飛行', characteristic: 'するどいめ', explain: 'タフで持久力に優れる。重たい荷物を乗せたまま乗せたまま、丸一日飛び続けても平気。' },
    { id: 23, name: 'アーボック', category: 'コブラ', type: '毒', characteristic: 'いかく、だっぴ', explain: 'おなかの模様が怖い顔に見える。弱い敵はその模様を見ただけで逃げ出してしまう。' },
    { id: 24, name: 'アーボ', category: 'へび', type: '毒', characteristic: 'いかく、だっぴ', explain: '育つほどにどんどん長くなる。夜中は木の枝にぐるぐるとからまって休む。' },
    { id: 25, name: 'ピカチュウ', category: 'ねずみ', type: '電気', characteristic: 'せいでんき', explain: '作る電気が強力なピカチュウほど、ほっぺのふくろは柔らかく、よく伸びる。' },
    { id: 26, name: 'ライチュウ', category: 'ねずみ', type: '電気', characteristic: 'せいでんき', explain: '電気袋がからっぽになると、尻尾をまっすぐに立てて、空気中の電気を集める。' },
    { id: 27, name: 'サンドパン', category: 'ねずみ', type: 'じめん', characteristic: 'すながくれ', explain: '湿度が低い土地で暮らすサンドパンほど、背中の棘の手触りは硬く滑らかになる。' },
    { id: 28, name: 'サンド', category: 'ねずみ', type: 'じめん', characteristic: 'すながくれ', explain: '乾燥した砂地で砂浴びをするのが好き。体についた汚れと水気を落とすのだ。' },
    { id: 29, name: 'ニドランメス', category: 'どくばり', type: '毒', characteristic: 'どくのトゲ、とうそうしん', explain: '雄よりも匂いに敏感。髭で風向きを確認しながら、風下で餌を探すのだ。' },
    { id: 30, name: 'ニドリーナ', category: 'どくばり', type: '毒', characteristic: 'どくのトゲ、とうそうしん', explain: '額のツノは、子供に餌を与えるときに刺さらないよう、退化したと考えられている。' },
    { id: 31, name: 'ニドクイン', category: 'ドリル', type: '毒、じめん', characteristic: 'どくのトゲ、とうそうしん', explain: '攻めるよりも守るほうが得意。鎧のような鱗で、いかなる攻撃からも子供を守る。' },
    { id: 32, name: 'ニドランオス', category: 'どくばり', type: '毒', characteristic: 'どくのトゲ、とうそうしん', explain: '額のツノには猛毒がある。警戒心が強く、大きな耳をいつもそばだてている。' },
    { id: 33, name: 'ニドリーノ', category: 'どくばり', type: '毒', characteristic: 'どくのトゲ、とうそうしん', explain: 'ダイヤモンドよりも硬いツノで、岩石を砕いて回る。月の石を探しているのだ。' },
    { id: 34, name: 'ニドキング', category: 'ドリル', type: '毒、じめん', characteristic: 'どくのトゲ、とうそうしん', explain: '暴れると手がつけられなくなるが、長年連れ添ったニドクインの前では、穏やかな顔になる。' },
    { id: 35, name: 'ピッピ', category: 'ようせい', type: 'フェアリー', characteristic: 'メロメロボディ、マジックガード', explain: '満月の夜、ピッピが集まってダンスをする様子を見ると、幸せになれると言われている。' },
    { id: 36, name: 'ピクシー', category: 'ようせい', type: 'フェアリー', characteristic: 'メロメロボディ、マジックガード', explain: 'ようせいの仲間で、めったに人前に出てこない。気配を感じて、すぐに逃げてしまうようだ。' },
    { id: 37, name: 'ロコン', category: 'きつね', type: '炎', characteristic: 'もらいび', explain: '子供だが、６本の尻尾が美しい。成長すると、さらに尻尾が増える。' },
    { id: 38, name: 'キュウコン', category: 'きつね', type: '炎', characteristic: 'もらいび', explain: '尻尾の一本一本に神通力が込められている。1000年生きると言われている。' },
    { id: 39, name: 'プリン', category: 'ふうせん', type: 'ノーマル、フェアリー', characteristic: 'メロメロボディ、かちき', explain: '肺活量はポケモン界でもトップクラス。相手が眠るまで子守唄を歌い続けるぞ。' },
    { id: 40, name: 'プクリン', category: 'ふうせん', type: 'ノーマル、フェアリー', characteristic: 'メロメロボディ、かちき', explain: '息を吸えば吸うほど膨らむ。不機嫌になると、体を大きく膨らませて、相手を威圧する。' },
    { id: 41, name: 'ズバット', category: 'コウモリ', type: '毒、飛行', characteristic: 'せいしんりょく', explain: '口から出す超音波で周りの様子を探る。狭い洞窟も器用に飛び回る。' },
    { id: 42, name: 'ゴルバット', category: 'コウモリ', type: '毒、飛行', characteristic: 'せいしんりょく', explain: '生き物の血液が好物。腹ペコの仲間に、吸った血を分け与えることもあるという。' },
    { id: 43, name: 'ナゾノクサ', category: '雑草', type: '草、毒', characteristic: 'ようりょくそ', explain: '月の光を浴びて動き出す。夜の間に、たねをあちこちにばら撒くため歩き回る。' },
    { id: 44, name: 'クサイハナ', category: '雑草', type: '草、毒', characteristic: 'ようりょくそ', explain: 'めしべが放つとても臭い匂いは、２キロ先まで届き、気を失わせる。' },
    { id: 45, name: 'ラフレシア', category: 'フラワー', type: '草、毒', characteristic: 'ようりょくそ', explain: '世界一大きな花びらは、歩くたびに揺れて、大量の毒花粉をばら撒いてしまう。' },
    { id: 46, name: 'パラス', category: 'きのこ', type: '虫、草', characteristic: 'ほうし、かんそうはだ', explain: '食っても食っても、背中に生えているきのこが、栄養を奪っていくのだ。' },
    { id: 47, name: 'パラセクト', category: 'きのこ', type: '虫、草', characteristic: 'ほうし、かんそうはだ', explain: '大きなキノコがパラセクトを操っている。よくマシェードと縄張り争いをしている。' },
    { id: 48, name: 'コンパン', category: 'こんちゅう', type: '虫、毒', characteristic: 'ふくがん、いろめがね', explain: '小さな目がたくさん集まって、大きな目になっている。夜になると、あかりに集まる。' },
    { id: 49, name: 'モルフォン', category: 'どくが', type: '虫、毒', characteristic: 'りんぷん、いろめがね', explain: 'ばら撒かれたりんぷんに触れると、体の感覚がおかしくなって、まっすぐに立っていられなくなる。' },
    { id: 50, name: 'ディグダ', category: 'もぐら', type: 'じめん', characteristic: 'すながくれ、ありじごく', explain: 'ディグダが通った後の大地は、ほどよく耕されて、最高の畑になる。' },
    { id: 51, name: 'ダグトリオ', category: 'もぐら', type: 'じめん', characteristic: 'すながくれ、ありじごく', explain: 'チームワークに優れたみつごのディグダ。地下100キロまで掘って、地震を起こすこともある。' },
    { id: 52, name: 'ニャース', category: 'ばけねこ', type: 'ノーマル', characteristic: 'ものひろい、テクニシャン', explain: 'ひかりものを集めるのが好き。機嫌が良い時は、トレーナーにもコレクションを見せてくれるぞ。' },
    { id: 53, name: 'ペルシアン', category: 'シャムネコ', type: 'ノーマル', characteristic: 'じゅうなん、テクニシャン', explain: 'きぐらいが高く、なつかせるのが大変。気に食わないことがあると、すぐに爪を立ててくる。' },
    { id: 54, name: 'コダック', category: 'あひる', type: '水', characteristic: 'しめりけ、ノーてんき', explain: 'いつも頭痛に悩んでいる。不思議な力を爆発させると、しばらく痛みは治るようだ。' },
    { id: 55, name: 'ゴルダック', category: 'あひる', type: '水', characteristic: 'しめりけ、ノーてんき', explain: '流れの穏やかな川にすむ。長い手足で水をかき分け、優雅な泳ぎを見せる。' },
    { id: 56, name: 'マンキー', category: 'ぶたざる', type: '格闘', characteristic: 'やる気、いかりのつぼ', explain: '前触れもなく突然怒る。暴れまくって誰もいなくなると、孤独に耐えられなくて、また怒る。' },
    { id: 57, name: 'オコリザル', category: 'ぶたざる', type: '格闘', characteristic: 'やる気、いかりのつぼ', explain: 'あまりにも怒りすぎて、そのまま死んでしまうことがあるほどだが、その死に顔はとても安らか。' },
    { id: 58, name: 'ガーディ', category: 'こいぬ', type: '炎', characteristic: 'いかく、もらいび', explain: '自分よりも大きな相手でも恐れずに立ち向かう、勇敢で頼もしい性格。' },
    { id: 59, name: 'ウインディ', category: 'でんせつ', type: '炎', characteristic: 'いかく、もらいび', explain: '一昼夜で10000キロの距離を駆け抜ける姿は、多くの人を魅了してきた。' },
    { id: 60, name: 'ニョロモ', category: 'おたま', type: '水', characteristic: 'ちょすい、しめりけ', explain: '歩くよりも泳ぐほうが得意。おなかの渦巻き模様は、すけて見える内臓の一部だ。' },
    { id: 61, name: 'ニョロゾ', category: 'おたま', type: '水', characteristic: 'ちょすい、しめりけ', explain: 'おなかの渦はじっと見ていると眠くなる。子守唄の代わりに、子供を寝付かせるのにも使う。' },
    { id: 62, name: 'ニョロボン', category: 'おたま', type: '水、格闘', characteristic: 'ちょすい、しめりけ', explain: '全身が筋肉の塊。寒い海でも、逞しい腕で流氷を砕き、突き進む。' },
    { id: 63, name: 'ケーシィ', category: 'ねんりき', type: 'エスパー', characteristic: 'シンクロ、せいしんりょく', explain: '寝ながら超能力を操る。夢の内容が、使う力に影響を与える。' },
    { id: 64, name: 'ユンゲラー', category: 'ねんりき', type: 'エスパー', characteristic: 'シンクロ、せいしんりょく', explain: 'サイコパワーで宙に浮いたまま寝る。弾力に優れた尻尾を枕がわりにするぞ。' },
    { id: 65, name: 'フーディン', category: 'ねんりき', type: 'エスパー', characteristic: 'シンクロ、せいしんりょく', explain: '非常に高い知能を持つ。生まれてから死ぬまでの出来事を、全て覚えているという。' },
    { id: 66, name: 'ワンリキー', category: 'かいりき', type: '格闘', characteristic: 'こんじょう、ノーガード', explain: '全身が筋肉になっており、子供ほどの大きさしかないのに、大人100人を投げ飛ばせる。' },
    { id: 67, name: 'ゴーリキー', category: 'かいりき', type: '格闘', characteristic: 'こんじょう、ノーガード', explain: 'すごく強靭な肉体なので、パワーセーブベルトをつけて、強さを制御している。' },
    { id: 68, name: 'カイリキー', category: 'かいりき', type: '格闘', characteristic: 'こんじょう、ノーガード', explain: '４本の腕を素早く動かし、あらゆる角度から休むことなく、パンチやチョップを叩き込む。' },
    { id: 69, name: 'マダツボミ', category: 'フラワー', type: '草、毒', characteristic: 'ようりょくそ', explain: 'ひょろっとした体つきだが、獲物をとらえる時の動きは、目にも止まらないほど素早い。' },
    { id: 70, name: 'ウツドン', category: 'ハエトリ', type: '草、毒', characteristic: 'ようりょくそ', explain: '葉っぱの部分はカッターになっていて、相手を切り裂く。口からなんでも溶かす液体を吐き出す。' },
    { id: 71, name: 'ウツボット', category: 'ハエトリ', type: '草、毒', characteristic: 'ようりょくそ', explain: 'ジャングルの奥地にウツボットばかりがいる地帯があって、行ったら２度と戻ってこれない。' },
    { id: 72, name: 'メノクラゲ', category: 'クラゲ', type: '水、毒', characteristic: 'クリアボディ、ヘドロえき', explain: '泳ぐ力は強くはない。浅い海の水面を漂いながら、獲物を探す。' },
    { id: 73, name: 'ドククラゲ', category: 'クラゲ', type: '水、毒', characteristic: 'クリアボディ、ヘドロえき', explain: '80本の触手は伸び縮み自由。網のように広げて獲物を捕らえ、どくばりを刺す。' },
    { id: 74, name: 'イシツブテ', category: 'がんせき', type: 'いわ、地面', characteristic: 'いしあたま、がんじょう', explain: '丸くて持ちやすいが、投げ合うには硬くて重い。雪玉のようにぶつけ合って遊ぶには危険だ。' },
    { id: 75, name: 'ゴローン', category: 'がんせき', type: 'いわ、地面', characteristic: 'いしあたま、がんじょう', explain: '苔のついた岩が大好物。ぼりぼりと音を立てながら、1日1トン以上食べる。' },
    { id: 76, name: 'ゴローニャ', category: 'メガトン', type: 'いわ、地面', characteristic: 'いしあたま、がんじょう', explain: 'ダイナマイトで爆破しても、傷一つつかない体だが、湿気や雨は大嫌い。' },
    { id: 77, name: 'ポニータ', category: 'ひのうま', type: '炎', characteristic: 'にげあし、もらいび', explain: '生まれたばかりでは立つのがやっと。だが、走るほどに足腰が鍛えられて、速度ががまして行く。' },
    { id: 78, name: 'ギャロップ', category: 'ひのうま', type: '炎', characteristic: 'にげあし、もらいび', explain: '走る速度は時速240キロ。たてがみの炎が激しく燃え、矢のように駆け抜ける。' },
    { id: 79, name: 'ヤドン', category: 'まぬけ', type: '水、エスパー', characteristic: '鈍感、マイペース', explain: '間抜けで鈍感。尻尾を食べられても痛みを感じないし、生え変わったことにも気づかない。' },
    { id: 80, name: 'ヤドラン', category: 'やどかり', type: '水、エスパー', characteristic: '鈍感、マイペース', explain: 'シェルダーに尻尾を噛まれて進化。シェルダーは尻尾から滲み出る甘みに、夢心地だ。' },
    { id: 81, name: 'レアコイル', category: 'じしゃく', type: '電気', characteristic: 'じりょく、がんじょう', explain: '3びきのコイルが連結した。強力な電波を放ち、周りの様子を観測する。' },
    { id: 82, name: 'コイル', category: 'じしゃく', type: '電気', characteristic: 'じりょく、がんじょう', explain: '体内の電気が切れてじめんに転がっていることもある。電池をあげると動き出すよ。' },
    { id: 83, name: 'カモネギ', category: 'かるがも', type: 'ノーマル、飛行', characteristic: 'するどいめ、せいしんりょく', explain: '持っている茎は大切な武器でもあり、刀を振るように、いろんなものを切ることができる。' },
    { id: 84, name: 'ドードー', category: 'ふたごどり', type: 'ノーマル、飛行', characteristic: 'にげあし、はやおき', explain: '突然変異で見つかった2つの頭を持つポケモン。時速100キロで走る。' },
    { id: 85, name: 'ドードリオ', category: 'みつごどり', type: 'ノーマル、飛行', characteristic: 'にげあし、はやおき', explain: '3つの頭が見ている前で、わずかでも隙を見せると、くちばしで激しくつつかれる。' },
    { id: 86, name: 'パウワウ', category: 'アシカ', type: '水', characteristic: 'あついしぼう、うるおいボディ', explain: '氷山で暮らすポケモン。頭の尖ったでっぱりで、氷を割って海を泳ぐ。' },
    { id: 87, name: 'ジュゴン', category: 'アシカ', type: '水、氷', characteristic: 'あついしぼう、うるおいボディ', explain: '全身が真っ白な毛で覆われている。寒さに強く、むしろ寒いほど元気になる。' },
    { id: 88, name: 'ベトベター', category: 'ヘドロ', type: '毒', characteristic: 'あくしゅう、ねんちゃく', explain: '工場の垂れ流すヘドロの廃液が主な餌なのだ。最近は数が減ってきた。' },
    { id: 89, name: 'ベトベトン', category: 'ヘドロ', type: '毒', characteristic: 'あくしゅう、ねんちゃく', explain: 'とにかく鼻が曲がるほど臭い。だが一部には、それがいいと言うベトベトンマニアも存在する。' },
    { id: 90, name: 'シェルダー', category: '2まいがい', type: '水', characteristic: 'シェルアーマー、スキルリンク', explain: '2枚の殻を開けたり閉じたりすることで後ろ向きに泳ぐ。そのスピードは結構早い。' },
    { id: 91, name: 'パルシェン', category: '2まいがい', type: '水、氷', characteristic: 'シェルアーマー、スキルリンク', explain: '殻が非常に硬く、ナパーム弾でも壊せない。攻撃する時だけ開く。' },
    { id: 92, name: 'ゴースト', category: 'ガス状', type: 'ゴースト、毒', characteristic: 'ふゆう', explain: 'ガス状の舌で舐められると、体の震えが止まらなくなり、やがては死にいたるという。' },
    { id: 93, name: 'ゴース', category: 'ガス状', type: 'ゴースト、毒', characteristic: 'ふゆう', explain: 'ガスから生まれた生命体。毒を含んだガスの体に包まれると、誰でも気絶する。' },
    { id: 94, name: 'ゲンガー', category: 'シャドー', type: 'ゴースト、毒', characteristic: 'のろわれボディ', explain: '満月の夜、影が勝手に動き出して笑うのは、ゲンガーの仕業に違いない。' },
    { id: 95, name: 'イワーク', category: 'いわへび', type: 'いわ、じめん', characteristic: 'いしあたま、がんじょう', explain: '地中を掘り進みながら、いろんな硬いものを取り込み、頑丈な体を作る。' },
    { id: 96, name: 'スリープ', category: 'さいみん', type: 'エスパー', characteristic: 'ふみん、よちむ', explain: '夢を喰らって生きるポケモン。ムンナやムシャーナと共通の祖先を持つと考えられている。' },
    { id: 97, name: 'スリーパー', category: 'さいみん', type: 'エスパー', characteristic: 'ふみん、よちむ', explain: '非常に危険なポケモンだが、安眠を求める人には救世主と呼ばれている。' },
    { id: 98, name: 'クラブ', category: 'サワガニ', type: '水', characteristic: 'かいりきバサミ、シェルアーマー', explain: '海の近くで見つかる。大きなハサミは、もぎ取っても後からまた生えてくる。' },
    { id: 99, name: 'キングラー', category: 'はさみ', type: '水', characteristic: 'かいりきバサミ、シェルアーマー', explain: '硬いハサミは1万馬力のパワーを持っているが、大きすぎて動きが鈍い。' },
    { id: 100, name: 'ビリリダマ', category: 'ボール', type: '電気', characteristic: 'ぼうおん、せいでんき', explain: 'モンスターボールが売り出されたのと同じ時期に発見された。何か関係があると言われる。' },
    { id: 101, name: 'マルマイン', category: 'ボール', type: '電気', characteristic: 'ぼうおん、せいでんき', explain: '少しの刺激の反応して爆発する。爆弾ボールというあだ名で怖がられている。' },
    { id: 102, name: 'タマタマ', category: 'たまご', type: '草、エスパー', characteristic: 'ようりょくそ', explain: 'たまごのように見えるが、立派なポケモン。テレパシーで仲間と交信しているらしいぞ。' },
    { id: 103, name: 'ナッシー', category: 'やしのみ', type: '草、エスパー', characteristic: 'ようりょくそ', explain: '3つの頭は別のことを考えている。自分以外は、あまり興味がないようだ。' },
    { id: 104, name: 'カラカラ', category: 'こどく', type: 'じめん', characteristic: 'いしあたま、ひらいしん', explain: '死んだ母親の骨をかぶる。夢を見て泣くこともあるけれど、涙を流すたびに強くなる。' },
    { id: 105, name: 'ガラガラ', category: 'ほねずき', type: 'じめん', characteristic: 'いしあたま、ひらいしん', explain: '悲しみを乗り越えて逞しく進化した。骨を武器にして勇敢に敵と渡り合う。' },
    { id: 106, name: 'サワムラー', category: 'キック', type: '格闘', characteristic: 'じゅんなん、すてみ', explain: '見事なバランス感覚。どんな姿勢でもキックを連続で放てるすごいやつ。' },
    { id: 107, name: 'エビワラー', category: 'パンチ', type: '格闘', characteristic: 'するどいめ、てつのこぶし', explain: '空気を切り裂くパンチ。掠っただけで火傷になる程、パンチのスピードは速いのだ。' },
    { id: 108, name: 'ベロリンガ', category: 'なめまわし', type: 'ノーマル', characteristic: 'マイペース、どんかん', explain: 'ねばねばした唾液に触れたまま放っておくと、ものすごい痒みがはじまり止まらなくなるぞ。' },
    { id: 109, name: 'ドガース', category: 'どくガス', type: '毒', characteristic: 'ふゆう、かがくへんかガス', explain: 'どくガスでパンパンの体。生ゴミの腐った匂いを求めて、ゴミ捨て場にやってくる。' },
    { id: 110, name: 'マタドガス', category: 'どくガス', type: '毒', characteristic: 'ふゆう', explain: 'どちらかが膨らむと、片方がしぼむ双子のドガース。いつも体内のどくガスを混ぜている。' },
    { id: 111, name: 'サイホーン', category: 'とげとげ', type: 'じめん、いわ', characteristic: 'ひらいしん、いしあたま', explain: '頭は悪いが力が強く、高層ビルも体当たりで粉々に粉砕する。' },
    { id: 112, name: 'サイドン', category: 'ドリル', type: 'じめん、いわ', characteristic: 'ひらいしん、いしあたま', explain: '進化して後ろ足だけで立つようになった。ツノでつくと、岩石にも穴を開けてしまう。' },
    { id: 113, name: 'ラッキー', category: 'たまご', type: 'ノーマル', characteristic: 'しぜんかいふく、てんのめぐみ', explain: 'たまごは栄養満点で味も抜群。高級な食材として扱われる。' },
    { id: 114, name: 'モンジャラ', category: 'ツルじょう', type: '草', characteristic: 'ようりょくそ、リーフガード', explain: '千切れても無限にのびるツルの奥の正体は、いまだ解明されていない。' },
    { id: 115, name: 'ガルーラ', category: 'おやこ', type: 'ノーマル', characteristic: 'はやおき、きもったま', explain: '腹の袋に子供がいるが、フットワークはとても軽い。素早いジャブで相手を威嚇。' },
    { id: 116, name: 'タッツー', category: 'ドラゴン', type: '水', characteristic: 'すいすい、スナイパー', explain: '潮の流れが穏やかな海に住む。襲われると真っ黒な墨を吐いて、その隙に逃げ出す。' },
    { id: 117, name: 'シードラ', category: 'ドラゴン', type: '水', characteristic: 'どくのとげ、スナイパー', explain: 'オスが子供を育てる。子育て中は、背中のとげの毒素が、強く濃くなる。' },
    { id: 118, name: 'トサキント', category: 'きんぎょ', type: '水', characteristic: 'すいすい、水のベール', explain: 'せびれ、むなびれ、おびれが優雅にたなびくので、水の踊り子と呼ばれる。' },
    { id: 119, name: 'アズマオウ', category: 'きんぎょ', type: '水', characteristic: 'すいすい、水のベール', explain: '秋になると、プロポーズのため体に脂がのってきて、とても綺麗な色に変化する。' },
    { id: 120, name: 'ヒトデマン', category: 'ほしがた', type: '水', characteristic: 'はっこう、しぜんかいふく', explain: '夏の終わりに浜辺に行くと、規則的なリズムで光るヒトデマンの群れが見られるよ。' },
    { id: 121, name: 'スターミー', category: 'なぞの', type: '水、エスパー', characteristic: 'はっこう、しぜんかいふく', explain: '強烈なサイコパワーを放つとき、コアと呼ばれる器官が七色に煌めく。' },
    { id: 122, name: 'バリヤード', category: 'バリアー', type: 'エスパー、フェアリー', characteristic: 'ぼうおん、フィルター', explain: '大きな手のひらは、パントマイムをするために発達したと考える学者も多い。' },
    { id: 123, name: 'ストライク', category: 'カマキリ', type: '虫、飛行', characteristic: 'むしのしらせ、テクニシャン', explain: '戦いを重ねるごとにカマの切れ味は上がる。大木も一刀両断に切り裂くぞ。' },
    { id: 124, name: 'ルージュラ', category: 'ひとがた', type: '氷、エスパー', characteristic: 'どんかん、よちむ', explain: 'ガラルのとある地域では、氷の女王と呼んでルージュラを恐れ崇めていた。' },
    { id: 125, name: 'エレブー', category: 'でんげき', type: 'でんき', characteristic: 'せいでんき', explain: '電気を狙うエレブーの対策に、地面ポケモンを置く発電所が多い。' },
    { id: 126, name: 'ブーバー', category: 'ひふき', type: '炎', characteristic: 'ほのおのからだ', explain: '炎で獲物を仕留める。ついついやりすぎて黒焦げにしてしまい後悔する。' },
    { id: 127, name: 'カイロス', category: 'クワガタ', type: '虫', characteristic: 'かいりきバサミ、かたやぶり', explain: 'ツノで互いを格付けする。太く立派なツノを持つカイロスほど異性に人気。' },
    { id: 128, name: 'ケンタロス', category: 'あばれうし', type: 'ノーマル', characteristic: 'いかく、いかりのつぼ', explain: '尻尾で自分の体を叩き出したら危険だぞ。猛スピードで突っ込んでくる。' },
    { id: 129, name: 'コイキング', category: 'さかな', type: '水', characteristic: 'すいすい', explain: '力もスピードもほとんどダメ。世界で一番弱くて情けないポケモンだ。' },
    { id: 130, name: 'ギャラドス', category: 'きょうあく', type: '水、飛行', characteristic: 'いかく', explain: '非常に凶暴な性格。口から出す破壊光線は、全てのものを焼き尽くす。' },
    { id: 131, name: 'ラプラス', category: 'のりもの', type: '水、氷', characteristic: 'ちょすい、シェルアーマー', explain: '賢く心優しいポケモン。綺麗な歌声を響かせながら、海を上を泳いでいく。' },
    { id: 132, name: 'メタモン', category: 'へんしん', type: 'ノーマル', characteristic: 'じゅうなん', explain: '全身の細胞を組み替えて、見たものそっくりにへんしんするが、力が抜けると元に戻る。' },
    { id: 133, name: 'イーブイ', category: 'しんか', type: 'ノーマル', characteristic: 'にげあし、てきおうりょく', explain: '不安定な遺伝子のおかげで、さまざまな進化の可能性を秘めている特殊なポケモン。' },
    { id: 134, name: 'シャワーズ', category: 'あわはき', type: '水', characteristic: 'ちょすい', explain: 'シャワーズの全身のヒレが小刻みに震え始めるのは、数時間後に雨が降るしるし。' },
    { id: 135, name: 'サンダース', category: 'かみなり', type: '電気', characteristic: 'ちくでん', explain: '怒ったり驚いたりすると、全身の毛が針のように逆立って、相手を貫く。' },
    { id: 136, name: 'ブースター', category: 'ほのお', type: '炎', characteristic: 'もらいび', explain: '体内に炎が溜まると、ブースターの体温も最高900度まで上がっていく。' },
    { id: 137, name: 'ポリゴン', category: 'バーチャル', type: 'ノーマル', characteristic: 'トレース、ダウンロード', explain: '最高の科学力を使い、世界で初めてプログラムにより作られた人工のポケモン。' },
    { id: 138, name: 'オムナイト', category: 'うずまき', type: 'いわ、水', characteristic: 'すいすい、シェルアーマー', explain: '絶滅した古代のポケモン。10本足で水をかき、漂うように泳ぐ。' },
    { id: 139, name: 'オムスター', category: 'うすまき', type: 'いわ、水', characteristic: 'すいすい、シェルアーマー', explain: '大きく重い殻のせいで動きが鈍くなり、獲物を取れずに絶滅したという。' },
    { id: 140, name: 'カブトプス', category: 'こうら', type: 'いわ、水', characteristic: 'すいすい、カブトアーマー', explain: '絶滅したと言われるが、一部の地域では結構普通に見かけるらしい。' },
    { id: 141, name: 'カブト', category: 'こうら', type: 'いわ、水', characteristic: 'すいすい、カブトアーマー', explain: '獲物を切り裂き体液を啜る。残った体は他のポケモンの餌になる。' },
    { id: 142, name: 'プテラ', category: 'かせき', type: 'いわ、飛行', characteristic: 'いしあたま、プレッシャー', explain: '古代の獰猛なポケモン。完璧な復元は今の科学でも不可能らしい。' },
    { id: 143, name: 'カビゴン', category: 'いねむり', type: 'ノーマル', characteristic: 'あついしぼう、めんえき', explain: '1日に食べ物を400キロ食べないと気が済まない。食べ終わると眠ってしまう。' },
    { id: 144, name: 'フリーザー', category: 'れいとう', type: '氷、飛行', characteristic: 'プレッシャー', explain: '青く美しい羽は氷でできていると言われる。長い尾をたなびかせ、雪山を飛ぶ。' },
    { id: 145, name: 'サンダー', category: 'でんげき', type: '電気、飛行', characteristic: 'プレッシャー', explain: '羽をこすり合わせると雷が落ちると言われている、伝説の鳥ポケモン。' },
    { id: 146, name: 'ファイヤー', category: 'かえん', type: '炎、飛行', characteristic: 'プレッシャー', explain: '羽ばたくと翼の炎が赤く美しく煌めく、伝説の鳥ポケモンの一匹。' },
    { id: 147, name: 'ミニリュウ', category: 'ドラゴン', type: 'ドラゴン', characteristic: 'だっぴ', explain: '滝壺など流れの激しい水辺で暮らしている。脱皮を繰り返して大きく育つ。' },
    { id: 148, name: 'ハクリュー', category: 'ドラゴン', type: 'ドラゴン', characteristic: 'だっぴ', explain: '綺麗な海や湖に住む。天候を操る力で風に乗り、そらへと登る。' },
    { id: 149, name: 'カイリュー', category: 'ドラゴン', type: 'ドラゴン、飛行', characteristic: 'せいしんりょく', explain: '溺れている人やポケモンを見つけると、助けずにはいられない心優しいポケモン。' },
    { id: 150, name: 'ミュウツー', category: '遺伝子', type: 'エスパー', characteristic: 'プレッシャー', explain: '一人の科学者が、何年も恐ろしい研究を続けた結果、誕生した。' },
    { id: 151, name: 'ミュウ', category: '新種', type: 'エスパー', characteristic: 'シンクロ', explain: 'あらゆる技を使うため、ポケモンの先祖と考える科学者がたくさんいる。' }
  ]
  

  def self.reaction(user_message)
    self.data.each do |data|
      if data[:name] == user_message[data[:name]] && user_message == data[:name]
        return data[:name] + '、' + data[:category] + 'ポケモン。' + data[:type] + 'タイプのポケモン。特性は' + data[:characteristic] + "。" + data[:explain]
      elsif data[:name] == user_message[data[:name]]
        return data[:name] + '、' + data[:category] + 'ポケモン。' + data[:type] + 'タイプのポケモン。特性は' + data[:characteristic] + '。' + data[:explain]
      end
    end
  end
end